### ISSUE TITLE
ReferenceError: Can't find variable: TEMPORARY

### ISSUE THREAD

**Issue by AndreasBackx** [legoritma/dpizer#1]
This happens when loading the website on Safari 8 on OSX Yosemite.

This error occurs at line 22 in main.js.

**Comment by legoritma** [comment]
This happens because only webkit browsers (chrome and opera) supports FileSystem API right now (source: http://caniuse.com/#feat=filesystem)

**For the future**
The API is deprecated and won't be implemented on other browsers. Luckily related functions can be replaced without this API, but it will take time.
